#!/usr/bin/env python
"""Kyber.enc(pk): generate a challenge and a shared key (c, K)"""

import os
from kyber import Kyber as KyberBuilder, DEFAULT_PARAMETERS

BIT_STRENGTH = os.environ.get("BIT") or "512"
PK_PATH = os.environ.get("PK") or "pk"
C_PATH = os.environ.get("C") or "c"
KEY_PATH = os.environ.get("KEY") or "key"

kyber_algorithm = "kyber_" + BIT_STRENGTH
Kyber = KyberBuilder(DEFAULT_PARAMETERS[kyber_algorithm])

with open(PK_PATH, "rb") as pkf:
    pk = pkf.read()

c, key = Kyber.enc(pk)

with open(C_PATH, "wb") as cf:
    cf.write(c)

with open(KEY_PATH, "wb") as keyf:
    keyf.write(key)

print(C_PATH, "and", KEY_PATH, "files written")
