#!/usr/bin/env python

import os
PK_PATH = os.environ.get("PK") or "pk"
SK_PATH = os.environ.get("SK") or "sk"

from kyber_py import Kyber512
pk, sk = Kyber512.keygen()

with open(PK_PATH, "wb") as pkf:
    pkf.write(pk)

with open(SK_PATH, "wb") as skf:
    skf.write(sk)

print(PK_PATH, "and", SK_PATH, "files written")
