#!/usr/bin/env python
"""Kyber.keygen(): generate a keypair (pk, sk)"""

import os
from kyber import Kyber as KyberBuilder, DEFAULT_PARAMETERS

BIT_STRENGTH = os.environ.get("BIT") or "512"
PK_PATH = os.environ.get("PK") or "pk"
SK_PATH = os.environ.get("SK") or "sk"

kyber_algorithm = "kyber_" + BIT_STRENGTH
Kyber = KyberBuilder(DEFAULT_PARAMETERS[kyber_algorithm])

pk, sk = Kyber.keygen()

with open(PK_PATH, "wb") as pkf:
    pkf.write(pk)

with open(SK_PATH, "wb") as skf:
    skf.write(sk)

print(PK_PATH, "and", SK_PATH, "files written")
