version: "3.9"
services:
  sslh:
    image: marcpartensky/sslh
    build: sslh
  paru:
    image: marcpartensky/paru
    build: paru
  jupyterhub:
    image: marcpartensky/jupyterhub
    build: jupyterhub
  jupyterlab:
    image: marcpartensky/jupyterlab
    build: jupyterlab
  honeygain:
    image: marcpartensky/honeygain
    build: honegain
