version: "3.9"
services:
  sslh:
    image: marcpartensky/sslh
    build: sslh
  paru:
    image: marcpartensky/paru
    build: paru
  jupyterhub:
    image: marcpartensky/jupyterhub
    build: jupyterhub
  jupyterlab:
    image: marcpartensky/jupyterlab
    build: jupyterlab
  honeygain:
    image: marcpartensky/honeygain
    build: honeygain
  pawns:
    image: marcpartensky/pawns
    build: pawns
  traffmonetizer:
    image: marcpartensky/traffmonetizer
    build: traffmonetizer
  pgweb:
    image: marcpartensky/pgweb
    build: pgweb
  nixos:
    image: marcpartensky/nixos
    build: nixos
  vaultwarden-ldap:
    image: marcpartensky/vaultwarden-ldap
    build: vaultwarden-ldap
  cloudflared:
    image: marcpartensky/cloudflared
    build: cloudflared
  sqlmap:
    image: marcpartensky/sqlmap
    build: sqlmap
  hydra:
    image: marcpartensky/hydra
    build: hydra
  yt-dlp:
    image: marcpartensky/yt-dlp
    build: yt-dlp
  gpg:
    image: marcpartensky/gpg
    build: gpg
    volumes:
      - /home/marc/Videos/Youtube:/srv/Youtube
  kyber:
    image: marcpartensky/kyber
    build: kyber
  tableau-server:
    image: marcpartensky/tableau-server
    build: tableau-server
  wallabag:
    image: marcpartensky/wallabag
    build: wallabag
  pqcrypto:
    image: marcpartensky/pqcrypto
    build: pqcrypto
  libsodium:
    image: marcpartensky/libsodium
    build: libsodium
  jupyterhub-singleuser:
    image: marcpartensky/jupyterhub-singleuser
    build: jupyterhub-singleuser
  gpt4all:
    image: marcpartensky/gpt4all
    build: gpt4all
  djankiserv:
    image: marcpartensky/djankiserv
    build: djankiserv
  postgres:
    image: marcpartensky/postgres
    build: postgres
  photography:
    image: marcpartensky/photography
    build: photography
  dbml-editor:
    image: marcpartensky/dbml-editor
    build: dbml-editor
  n8n:
    image: marcpartensky/n8n
    build: n8n
  etherpad:
    image: marcpartensky/etherpad
    build: 
      context: etherpad
      args:
        ETHERPAD_PLUGINS: |
          ep_align
          ep_headings2
          ep_font_size
          ep_table_of_contents
          ep_adminpads3
          ep_countable
          ep_mathjax
          ep_webhooks
          ep_spellcheck
          ep_font_family
          ep_cursortrace
          ep_who_did_what
          ep_workspaces
          ep_print
          ep_mammoth
          ep_scrolltoanchor
          ep_comments_page
          ep_line_spacing
          ep_copy_paste_select_all
          ep_padlisting
          ep_pad-lister
          ep_author_hover
          ep_openid_connect
          ep_user_displayname
          ep_dividing_line
          ep_author_neat2
          ep_stable_authorid

        # ep_authentication
        # ep_oauth2
        # ep_embedded_hyperlinks
        # ep_padlist2
        # ep_small_list
        # ep_set_title_on_pad # j'aime pas
        # ep_desktop_notifications # mal codé
        # ep_markdown
        # Bugués
        # ep_themes
        # ep_tables4
        # ep_tables5
        # ep_post_data
        # ep_tableau
        # ep_previewimages
        # ep_allmende
        # ep_embedmedia
        # ep_whiteboard
  beekeeper-studio:
    image: marcpartensky/beekeeper-studio
    build: beekeeper-studio
