version: "3.9"
services:
  sslh:
    image: marcpartensky/sslh
    build: sslh
  paru:
    image: marcpartensky/paru
    build: paru
  jupyterhub:
    image: marcpartensky/jupyterhub
    build: jupyterhub
  jupyterlab:
    image: marcpartensky/jupyterlab
    build: jupyterlab
  honeygain:
    image: marcpartensky/honeygain
    build: honeygain
  pawns:
    image: marcpartensky/pawns
    build: pawns
  traffmonetizer:
    image: marcpartensky/traffmonetizer
    build: traffmonetizer
  pgweb:
    image: marcpartensky/pgweb
    build: pgweb
  nixos:
    image: marcpartensky/nixos
    build: nixos
  vaultwarden-ldap:
    image: marcpartensky/vaultwarden-ldap
    build: vaultwarden-ldap
  cloudflared:
    image: marcpartensky/cloudflared
    build: cloudflared
  sqlmap:
    image: marcpartensky/sqlmap
    build: sqlmap
  hydra:
    image: marcpartensky/hydra
    build: hydra
  yt-dlp:
    image: marcpartensky/yt-dlp
    build: yt-dlp
  gpg:
    image: marcpartensky/gpg
    build: gpg
    volumes:
      - /home/marc/Videos/Youtube:/srv/Youtube
  kyber:
    image: marcpartensky/kyber
    build: kyber
  tableau-server:
    image: marcpartensky/tableau-server
    build: tableau-server
  wallabag:
    image: marcpartensky/wallabag
    build: wallabag
  pqcrypto:
    image: marcpartensky/pqcrypto
    build: pqcrypto
  libsodium:
    image: marcpartensky/libsodium
    build: libsodium
  jupyterhub-singleuser:
    image: marcpartensky/jupyterhub-singleuser
    build: jupyterhub-singleuser
