version: "3.9"
services:
  sslh:
    image: marcpartensky/sslh
    build: sslh
  paru:
    image: marcpartensky/paru
    build: paru
  jupyterhub:
    image: marcpartensky/jupyterhub
    build: jupyterhub
  jupyterlab:
    image: marcpartensky/jupyterlab
    build: jupyterlab
  honeygain:
    image: marcpartensky/honeygain
    build: honeygain
  pawns:
    image: marcpartensky/pawns
    build: pawns
  traffmonetizer:
    image: marcpartensky/traffmonetizer
    build: traffmonetizer
  pgweb:
    image: marcpartensky/pgweb
    build: pgweb
  nixos:
    image: marcpartensky/nixos
    build: nixos
  vaultwarden-ldap:
    image: marcpartensky/vaultwarden-ldap
    build: vaultwarden-ldap
  cloudflared:
    image: marcpartensky/cloudflared
    build: cloudflared
